export default function Home() {
    return (<div id="experience" className="mb-4"><div className="mb-1.5 uppercase tracking-wide text-lg text-rose-600 dark:text-green-100 font-semibold">Experience</div>
    <p className="mt-2 text-black dark:text-slate-300">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis tellus at orci iaculis ultrices. Curabitur imperdiet enim elementum facilisis pellentesque. Morbi facilisis auctor orci, ac convallis leo sodales a. Donec vel sagittis lectus, feugiat hendrerit libero. Suspendisse id lacus et ipsum fringilla sodales. Ut sed justo turpis. Sed nec elit congue, pretium orci et, venenatis urna. Integer id suscipit libero. Sed ac aliquam risus, non bibendum elit. Quisque a tincidunt sapien, ac cursus leo. Duis ut mauris lorem. Suspendisse cursus libero et ipsum viverra ornare. Vivamus quis mi justo. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos..
    
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis tellus at orci iaculis ultrices. Curabitur imperdiet enim elementum facilisis pellentesque. Morbi facilisis auctor orci, ac convallis leo sodales a. Donec vel sagittis lectus, feugiat hendrerit libero. Suspendisse id lacus et ipsum fringilla sodales. Ut sed justo turpis. Sed nec elit congue, pretium orci et, venenatis urna. Integer id suscipit libero. Sed ac aliquam risus, non bibendum elit. Quisque a tincidunt sapien, ac cursus leo. Duis ut mauris lorem. Suspendisse cursus libero et ipsum viverra ornare. Vivamus quis mi justo. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos..
    
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis tellus at orci iaculis ultrices. Curabitur imperdiet enim elementum facilisis pellentesque. Morbi facilisis auctor orci, ac convallis leo sodales a. Donec vel sagittis lectus, feugiat hendrerit libero. Suspendisse id lacus et ipsum fringilla sodales. Ut sed justo turpis. Sed nec elit congue, pretium orci et, venenatis urna. Integer id suscipit libero. Sed ac aliquam risus, non bibendum elit. Quisque a tincidunt sapien, ac cursus leo. Duis ut mauris lorem. Suspendisse cursus libero et ipsum viverra ornare. Vivamus quis mi justo. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos..
    
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis tellus at orci iaculis ultrices. Curabitur imperdiet enim elementum facilisis pellentesque. Morbi facilisis auctor orci, ac convallis leo sodales a. Donec vel sagittis lectus, feugiat hendrerit libero. Suspendisse id lacus et ipsum fringilla sodales. Ut sed justo turpis. Sed nec elit congue, pretium orci et, venenatis urna. Integer id suscipit libero. Sed ac aliquam risus, non bibendum elit. Quisque a tincidunt sapien, ac cursus leo. Duis ut mauris lorem. Suspendisse cursus libero et ipsum viverra ornare. Vivamus quis mi justo. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos..
    
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis tellus at orci iaculis ultrices. Curabitur imperdiet enim elementum facilisis pellentesque. Morbi facilisis auctor orci, ac convallis leo sodales a. Donec vel sagittis lectus, feugiat hendrerit libero. Suspendisse id lacus et ipsum fringilla sodales. Ut sed justo turpis. Sed nec elit congue, pretium orci et, venenatis urna. Integer id suscipit libero. Sed ac aliquam risus, non bibendum elit. Quisque a tincidunt sapien, ac cursus leo. Duis ut mauris lorem. Suspendisse cursus libero et ipsum viverra ornare. Vivamus quis mi justo. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos..</p></div>)
}